services:
  loki:
    image: grafana/loki:latest
    container_name: aivn-loki
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-version" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - aio-network

  prometheus:
    image: prom/prometheus:latest
    container_name: aivn-prometheus
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus:/etc/prometheus
    entrypoint:
      - "/bin/sh"
      - "/etc/prometheus/entrypoint.sh"
    networks:
      - aio-network


  grafana:
    image: grafana/grafana:latest
    container_name: aivn-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - aio-network

  promtail:
    image: grafana/promtail:latest
    container_name: aivn-promtail
    restart: unless-stopped
    depends_on:
      - loki
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aio-network

networks:
  aio-network:
    external: true

volumes:
  grafana-storage: {}